name: Build and Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x86_64, aarch64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Qt (Linux)
      if: runner.os == 'Linux'
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.4.0'
        host: 'linux'
        target: 'desktop'
        arch: ${{ matrix.arch }}
        dir: "$HOME/Qt6.4.0"

    - name: Set up Qt (Windows)
      if: runner.os == 'Windows'
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.4.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: "$env:QT_DIR"

    - name: Build (Linux)
      if: runner.os == 'Linux'
      run: |
        mkdir build
        cd build
        cmake -G "Unix Makefiles" -DCMAKE_PREFIX_PATH=$HOME/Qt6.4.0/6.4.0/gcc_64 ..
        make

    - name: Build (Windows)
      if: runner.os == 'Windows'
      run: |
        mkdir build
        cd build
        cmake -G "NMake Makefiles" -DCMAKE_PREFIX_PATH=$env:QT_DIR/6.4.0/msvc2019_64 ..
        nmake

    - name: Package (Windows)
      if: runner.os == 'Windows'
      run: |
        cd build
        cpack -G ZIP
      env:
        PATH: $env:QT_DIR/6.4.0/msvc2019_64/bin;$PATH

    - name: Upload Artifact (Windows)
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: build/*.zip
