name: Build and Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.4.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: "$env:QT_DIR"

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -G "NMake Makefiles" -DCMAKE_PREFIX_PATH=$env:QT_DIR/6.4.0/msvc2019_64 ..
      shell: cmd

    - name: Build
      run: |
        cd build
        nmake
      shell: cmd

    - name: Deploy using windeployqt
      run: |
        cd build
        $env:QT_DIR/6.4.0/msvc2019_64/bin/windeployqt.exe --release --no-compiler-runtime --no-opengl-sw --no-angle --no-quick-import --no-system-d3d-compiler --no-virtualkeyboard .\Countdown.exe
      shell: pwsh

    - name: Package
      run: |
        cd build
        powershell Compress-Archive -Path * -DestinationPath ../Countdown_windows_x86_64.zip
      shell: pwsh

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: Countdown_windows_x86_64.zip

    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Countdown_windows_x86_64.zip
        asset_name: Countdown_windows_x86_64.zip
        asset_content_type: application/zip
