name: Build and Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.2.4'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        aqtversion: "==3.2.*"

    - name: Configure CMake
      run: |
        mkdir build
        cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release
      shell: cmd

    - name: Build
      run: |
        cd build
        cmake --build .
      shell: cmd

    - name: Deploy using windeployqt
      run: |
        cd build
        ls
        windeployqt --release --no-opengl-sw --no-angle --no-quick-import --no-system-d3d-compiler --no-virtualkeyboard Countdown.exe
      shell: pwsh

    - name: Package
      run: |
        cd build
        powershell Compress-Archive -Path * -DestinationPath ../countdown_windows.zip
      shell: pwsh

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: countdown_windows.zip
